version: '3.3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - my-db:/var/lib/postgresql
    ports:
      - '5432:5432'

# Names our volume
volumes:
  my-db:
