version: '3.3'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - my-db:/var/lib/postgresql
    ports:
      - '5432:5432'

  app:
    container_name: library
    build: .
    ports:
      - 8000:8000
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env

volumes:
  my-db: